Barcode correction
broadinstitute/epi-SHARE-seq-pipeline pull request #115
Opened 2023-05-09 14:17 UTC by mei-knudson

Key changes:
- Producing raw FASTQs in demultiplex
- Correcting FASTQs in share-seq
- New trimming code

2023-05-09 14:21 UTC, sidwekhande commented
There's a lot of commits here that are old and should not be merged. We should fix before merging. Everything before d05c3f7 should not be included.

2023-05-10 20:06 UTC, emattei requested changes

2023-05-10 20:06 UTC, emattei commented on share-seq.wdl
> +import "tasks/raise_exception.wdl" as exception_handler
Is this needed?

2023-05-18 14:21 UTC, emattei approved these changes

2023-05-18 14:22 UTC, emattei commented
For a later iteration:
- The trim for 10x should work also for non-multiome.
- We want to output the corrected FASTQs to the table.

2023-05-18 14:22 UTC, merged