Michael nums output
broadinstitute/epi-SHARE-seq-pipeline pull request #136
Opened 2023-08-31 18:55 UTC by shriverm1

[https://docs.google.com/document/d/1trlt0FtqX527JK6M4OLg10y7I-EweiAVHbABo1wXVGE/edit?usp=sharing](url)

[https://docs.google.com/document/d/1duWjRKXYQZbo5djke4vPvQICbzMwJW0QUGggcyTE-mE/edit?usp=sharing](url)

2023-09-07 15:28 UTC, emattei requested changes
Workflow is not valid, cannot be validated with womtools

2023-09-18 16:58 UTC, sidwekhande commented on src/python/joint_cell_plotting.py
will refactor this code to use metrics_df rather than reading the barcode file.

2023-09-18 17:11 UTC, sidwekhande commented on src/python/qc_atac_compute_tss_enrichment.py
moving this set of code outside the `plot_tss_enrichment` function. perhaps into the `compute_tss_enrichment` function

2023-09-18 17:13 UTC, sidwekhande commented on tasks/share_task_archr.wdl
will remove this, maybe will pass ArchR cut-offs straight into HTML task

2023-09-18 17:20 UTC, sidwekhande commented on src/python/qc_atac_compute_tss_enrichment.py
also, not sure where this file (with two scores) is being used. not part of html report. need in LIMS?

2023-09-18 17:55 UTC, sidwekhande commented on share-seq.wdl
add RNA cutoffs as well, for sake of completeness?

2023-09-20 22:16 UTC, sidwekhande commented on src/python/write_html.py
needs refactoring.
- better handling of numeric formatting
- remove commented old code
-

2023-09-20 22:20 UTC, sidwekhande commented on tasks/share_task_archr.wdl
this is required only if we want to report the cut-offs used in ArchR, which looks like are different from the ones we use in the joint plot

2023-09-20 22:51 UTC, sidwekhande commented on src/python/write_html.py
functions defined within in main.

2023-09-20 23:18 UTC, sidwekhande commented
workflow is now valid, and ironed out the major bugs. branch produces stable outputs, but needs refactoring.

2025-03-18 17:52 UTC, closed without merging