HTML report, integer logging, library size plot update
broadinstitute/epi-SHARE-seq-pipeline pull request #29
Opened 2022-07-26 17:07 UTC by nchernia

- All plots and log files reported in HTML report
- Integers logged; these can be set as outputs though are not currently
- Library size plot changed to png, produces two, adds in elbow finder

2022-07-26 22:04 UTC, emattei commented on dockerfiles/share_task_html_report.dockerfile
> +COPY src/python /software
Could you please just add the specific file you are using? I started to change this in the other dockers as well.

2022-07-26 22:06 UTC, emattei commented on dockerfiles/share_task_html_report.dockerfile
> +MAINTAINER Neva Durand
this should be 

LABEL maintainer = "Neva Durand"

2022-07-26 22:08 UTC, emattei commented on workflows/subwf-rna-single-organism.wdl
> +	Int rna_aligned_multimap = log_rna.rna_aligned_multimap
Indentation is off

2022-07-26 22:10 UTC, emattei commented on workflows/subwf-rna-single-organism.wdl
> +        Int rna_duplicate_reads = log_rna.rna_duplicate_reads
The naming is not consistent with the other outputs
rna_total_reads
instead of:
share_rna_total_reads

2022-07-26 22:11 UTC, emattei commented on workflows/subwf-atac-single-organism.wdl
> +        Int atac_duplicate_reads = log_atac.atac_duplicate_reads
The naming is not consistent with the other outputs
atac_total_reads
instead of:
share_atac_total_reads

2022-07-26 22:16 UTC, emattei commented on tasks/share_task_log_rna.wdl
> +        docker: 'ubuntu:latest'
I know that this is just for awk but we should never use 'latest' as the docker tag.
There must also be a much smaller image that has awk. probably alpine.

If you want we can change this after

2022-07-26 22:18 UTC, emattei commented on tasks/share_task_log_atac.wdl
> +        docker: 'ubuntu:latest'
same thing here as in the log rna

2022-07-26 22:28 UTC, emattei commented on share-seq.wdl
> +            share_rna_seurat_raw_violin_plot = rna.share_rna_seurat_raw_violin_plot,
example for line 145 if you decide to change the name in the task `rna_feature_reads = rna.share_rna_feature_reads`

suggestion for line 150, you could reduce that to  `rna_qc_library_plot = rna.share_qc_library_plot`

2022-07-26 22:31 UTC, emattei requested changes
If possible you would make me happy if you could make the output names consistent with the others.

All the other changes that are not about the output variable names should be implemented.

Thank you, looks very good.

2022-07-27 10:58 UTC, nchernia commented
Made all these changes and reran and it's working. Can you merge?

2022-07-27 13:04 UTC, emattei approved these changes

2022-07-27 13:04 UTC, merged